### ISSUE TITLE
xsltproc compatible

### ISSUE THREAD

**Issue by drzraf** [sflynn1812/xslt-diff#1]
xsltproc does not support `msxsl:node-set()`

**Comment by sflynn1812** [comment]
I can publish a release without that code.  Removing that function should allow for it to work the same way in other xslt processors, but Microsoft XSLT required them.

**Comment by sflynn1812** [comment]
I added a new branch without the node-set references if you want to try it out and let me know.

**Comment by drzraf** [comment]
I think removing `msxsl:node-set()` isn't enough by itself. Do you know what would be the xsltproc compatible syntax?

**Comment by sflynn1812** [comment]
I will be downloading xslt proc to see what is going on.  There is a known stackoverflow problem for larger XML files that I have come up with a way to fix, but have not implemented it yet.

**Comment by sflynn1812** [comment]
I fixed the xsltproc version and did some surface level testing and it is working.  It uses the exslt node-set function instead of the Microsoft version.

**Comment by sflynn1812** [comment]
it's fixed for xsltproc in the latest xsltproc branch release.  It needed a different node-set library/
    On Saturday, November 17, 2018, 4:07:07 PM EST, Raphaël Droz <notifications@github.com> wrote:  
 
 
I think removing msxsl:node-set() isn't enough by itself. Do you know what would be the xsltproc compatible syntax?

**Comment by drzraf** [comment]
Thank you, it works great under xsltproc now!
Note 1: in `README.md` => `input.xml` => `<root>` instead of `</root>`
Note 2: could you please remove my above (named) quote? I was mistaken and removed my comment afterwards btw.
